version: "3.9"

# Common environment variables template
x-common-variables: &common-variables
  http_proxy: "${PROXY_SERVER}"
  https_proxy: "${PROXY_SERVER}"
  HTTP_PROXY: "${PROXY_SERVER}"
  HTTPS_PROXY: "${PROXY_SERVER}"
  no_proxy: "${PROXY_BYPASS}"
  NO_PROXY: "${PROXY_BYPASS}"
  TZ: "${TIMEZONE:-UTC}"

# Common bridge configuration for all MCP bridge services
x-bridge-config: &bridge-config
  extra_hosts:
    - "host.docker.internal:host-gateway"
  restart: unless-stopped
  networks:
    - mcpnet

# Common health check configuration
x-health-check: &health-check
  interval: ${HEALTH_CHECK_INTERVAL:-30}s
  timeout: 10s
  retries: 3
  start_period: 40s

# Common resource limits for bridge services
x-bridge-resources: &bridge-resources
  limits:
    memory: ${DEFAULT_BRIDGE_MEMORY_LIMIT:-256m}
    cpus: '${DEFAULT_BRIDGE_CPU_LIMIT:-0.3}'

# Include network configuration
include:
  - compose.net.yml

services:
  # Context7 MCP Bridge - AI/ML documentation service
  context7-bridge:
    image: supercorp/supergateway:latest
    container_name: context7-bridge
    env_file: ../.env
    
    # Use common bridge configuration
    <<: *bridge-config
    
    environment:
      <<: *common-variables
      CONTEXT7_API_KEY: "${CONTEXT7_API_KEY}"

    expose:
      - "9030"

    command:
      - --stdio
      - "npx -y @upstash/context7-mcp@latest"
      - --port
      - "9030"
      - --ssePath
      - "/sse"
      - --messagePath
      - "/message"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9030/sse | head -c 1 >/dev/null 2>&1 || exit 1"]
      <<: *health-check

    deploy:
      resources:
        <<: *bridge-resources
        limits:
          memory: ${CONTEXT7_BRIDGE_MEMORY_LIMIT:-256m}
          cpus: '${CONTEXT7_BRIDGE_CPU_LIMIT:-0.3}'
        reservations:
          memory: ${CONTEXT7_BRIDGE_MEMORY_RESERVATION:-128m}
          cpus: '${CONTEXT7_BRIDGE_CPU_RESERVATION:-0.2}'

    profiles: ["ai", "all"]

    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILE:-3}"
        labels: "service=context7-bridge,profile=ai"

    security_opt:
      - no-new-privileges:true

  # Gistpad MCP Bridge - GitHub Gist management service
  gistpad-bridge:
    image: supercorp/supergateway:latest
    container_name: gistpad-bridge
    env_file: ../.env
    
    # Use common bridge configuration
    <<: *bridge-config
    
    environment:
      <<: *common-variables
      GITHUB_TOKEN: "${GITHUB_TOKEN}"

    expose:
      - "9010"

    command:
      - --stdio
      - "npx -y gistpad-mcp --daily --starred --archived"
      - --port
      - "9010"
      - --ssePath
      - "/sse"
      - --messagePath
      - "/message"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9010/sse | head -c 1 >/dev/null 2>&1 || exit 1"]
      <<: *health-check

    deploy:
      resources:
        <<: *bridge-resources
        limits:
          memory: ${GISTPAD_BRIDGE_MEMORY_LIMIT:-256m}
          cpus: '${GISTPAD_BRIDGE_CPU_LIMIT:-0.3}'
        reservations:
          memory: ${GISTPAD_BRIDGE_MEMORY_RESERVATION:-128m}
          cpus: '${GISTPAD_BRIDGE_CPU_RESERVATION:-0.2}'

    profiles: ["ai", "all"]

    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILE:-3}"
        labels: "service=gistpad-bridge,profile=ai"

    security_opt:
      - no-new-privileges:true

    volumes:
      - ${LOG_DIR:-./logs}:/logs
      - gistpad_cache:/tmp/gistpad-cache

# Additional volume for gistpad cache
volumes:
  gistpad_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR:-./data}/gistpad-cache