# PostgreSQL Database Service - Production-ready database
services:
  postgres:
    image: postgres:15-alpine
    container_name: mcp-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mcp_gateway}
      POSTGRES_USER: ${POSTGRES_USER:-mcp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mcp_user} -d ${POSTGRES_DB:-mcp_gateway}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - mcpnet

    # Profiles for selective startup
    profiles: ["database", "all", "minimal", "core"]

# Additional volumes for PostgreSQL
volumes:
  postgres_data:
    driver: local