version: "3.9"

# Common environment variables template
x-common-variables: &common-variables
  http_proxy: "${PROXY_SERVER}"
  https_proxy: "${PROXY_SERVER}"
  HTTP_PROXY: "${PROXY_SERVER}"
  HTTPS_PROXY: "${PROXY_SERVER}"
  no_proxy: "${PROXY_BYPASS}"
  NO_PROXY: "${PROXY_BYPASS}"
  TZ: "${TIMEZONE:-UTC}"

# Common health check configuration
x-health-check: &health-check
  interval: ${HEALTH_CHECK_INTERVAL:-30}s
  timeout: 10s
  retries: 3
  start_period: 40s

# Include network configuration
include:
  - compose.net.yml

services:
  # MCP Gateway with Admin UI - Core service
  mcp-gateway:
    image: ghcr.io/ibm/mcp-context-forge:0.8.0
    container_name: mcp-gateway
    ports:
      - "${MCP_GATEWAY_PORT:-4444}:4444"
    
    environment:
      # UI and Admin API configuration
      MCPGATEWAY_UI_ENABLED: "true"
      PLUGINS_ENABLED: "true"
      MCPGATEWAY_ADMIN_API_ENABLED: "true"
      HOST: "0.0.0.0"
      PORT: "4444"
      
      # Authentication configuration
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      BASIC_AUTH_USER: "${BASIC_AUTH_USER}"
      BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
      AUTH_REQUIRED: "${AUTH_REQUIRED:-true}"
      
      # Platform administrator configuration
      PLATFORM_ADMIN_EMAIL: "${PLATFORM_ADMIN_EMAIL}"
      PLATFORM_ADMIN_PASSWORD: "${PLATFORM_ADMIN_PASSWORD}"
      PLATFORM_ADMIN_FULL_NAME: "${PLATFORM_ADMIN_FULL_NAME}"
      
      # Database configuration - PostgreSQL for production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-mcp_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-mcp_gateway}"
      
      # Common environment variables
      <<: *common-variables

    volumes:
      - ${DATA_DIR:-./data}/mcp:/data
      - ${LOG_DIR:-./logs}:/logs

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4444/health || exit 1"]
      <<: *health-check

    deploy:
      resources:
        limits:
          memory: ${MCP_GATEWAY_MEMORY_LIMIT:-512m}
          cpus: '${MCP_GATEWAY_CPU_LIMIT:-0.5}'
        reservations:
          memory: ${MCP_GATEWAY_MEMORY_RESERVATION:-256m}
          cpus: '${MCP_GATEWAY_CPU_RESERVATION:-0.25}'

    networks:
      - mcpnet

    depends_on:
      postgres:
        condition: service_healthy

    # Profiles for selective startup
    profiles: ["core", "all", "minimal"]

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILE:-3}"
        labels: "service=mcp-gateway,profile=core"

    # Security configuration
    security_opt:
      - no-new-privileges:true
    
    # User configuration (non-root)
    user: "${MCP_GATEWAY_USER_ID:-1000}:${MCP_GATEWAY_GROUP_ID:-1000}"